# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  pagers:
    - pager: diff-so-fancy
    - externalDiffCommand: difft --color=always
    - pager: delta --dark --paging=never
